/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import static citasmedicas.CItasMedicas.nombreUsuario;
import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author angel
 */
public class FrmDoctores extends javax.swing.JFrame {

    /**
     * Creates new form FrmDoctores
     */
    public String Userl = nombreUsuario;

    public FrmDoctores() {
        initComponents();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Consultorio");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Hora");
        modeloTabla.addColumn("Paciente");
        Image icon = new ImageIcon(getClass().getResource("/Recursos/doctor.png")).getImage();
        this.setIconImage(icon);
        txtUser.setText(Userl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consultas = new javax.swing.JTable();
        btnMostar = new javax.swing.JPanel();
        lblGenerar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citas Doctores");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Consultas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Consultorio", "Fecha", "Hora", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Consultas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 500, 190));

        btnMostar.setBackground(new java.awt.Color(79, 175, 203));
        btnMostar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostarMouseClicked(evt);
            }
        });

        lblGenerar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblGenerar.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerar.setText("MOSTRAR CITRAS");
        lblGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnMostarLayout = new javax.swing.GroupLayout(btnMostar);
        btnMostar.setLayout(btnMostarLayout);
        btnMostarLayout.setHorizontalGroup(
            btnMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMostarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGenerar)
                .addGap(22, 22, 22))
        );
        btnMostarLayout.setVerticalGroup(
            btnMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnMostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 180, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Citas:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostarMouseClicked
        System.out.println(Userl);
        String f = "{'doctor': '" + Userl + "'}";
        MongoClient mongoClient = new MongoClient("localhost", 27017);
        MongoDatabase database = mongoClient.getDatabase("consultorio");

        MongoCollection<Document> collection = database.getCollection("doctores");
        MongoCollection<Document> col = database.getCollection("citas");

        Document filtro = Document.parse(f);

        List<Document> citas = col.find(filtro).into(new ArrayList<>());

        List<Document> doctores = collection.find().into(new ArrayList<>());

        System.out.println(citas);

        DefaultTableModel model = (DefaultTableModel) Consultas.getModel();
        for (Document cita : citas) {
            String nombreDoctor = cita.getString("doctor");
            for (Document doctor : doctores) {
                String nombre = doctor.getString("nombre");
                if (nombreDoctor.equals(nombre)) {
                    Object[] rowData = {cita.getString("consultorio"), cita.getString("fecha"), cita.getString("hora"), cita.getString("paciente")};
                    model.addRow(rowData);
                    break;
                }
            }
        }

    }//GEN-LAST:event_btnMostarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDoctores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Consultas;
    private javax.swing.JPanel btnMostar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGenerar;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
